set(sirius_solver_FOUND FALSE)

if(NOT sirius_solver_ROOT)
    set(sirius_solver_ROOT $ENV{sirius_solver_ROOT})
endif()
message(STATUS "sirius_solver_ROOT: ${sirius_solver_ROOT}")
if(NOT sirius_solver_ROOT)
    message(FATAL_ERROR "sirius_solver_ROOT: not found")
else()
    set(CMAKE_MODULE_PATH_BACKUP ${CMAKE_MODULE_PATH})
    set(CMAKE_MODULE_PATH "")
    set(sirius_solver_DIR "${sirius_solver_ROOT}/cmake")
    find_package(sirius_solver REQUIRED)
    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH_BACKUP})
endif()
