name: CentOS

on:
  push:
    branches:
      - main
      - feature/*
      - antares_integration
      - fix/*
  release:
    types: [ created ]

env:
  IS_RELEASE: ${{ github.event_name == 'workflow_dispatch' }}

jobs:

  build_sirius:
    name: build sirius
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build sirius using docker image
        run: |
          docker build -t centos7-sirius -f docker/Dockerfile .

      - name: create a container without starting it && retrieve the .tgz
        run: |
             container_id=$(docker create centos7-sirius)
             docker cp $container_id:/centos-7_sirius-solver.zip /tmp

      - name: Publish assets
        if: ${{ env.IS_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.event.inputs.release_tag }}
        run: |
          gh release upload "$tag" /tmp/centos-7_sirius-solver.zip
